NFACTORS=5;
NRUNS=6;
[S,X]=cordexch(NFACTORS,NRUNS,'linear');
S_linear = S
X_linear = X;
NFACTORS=5;
NRUNS=16;
[S,X]=cordexch(NFACTORS,NRUNS,'interaction');
S_interaction = S
X_interaction = X;
NFACTORS=5;
NRUNS=11;
[S,X]=cordexch(NFACTORS,NRUNS,'purequadratic');
S_purequadratic = S
X_purequadratic = X;
NFACTORS=5;
NRUNS=21;
[S,X]=cordexch(NFACTORS,NRUNS,'quadratic');
S_quadratic = S
X_quadratic = X;
